In [1]:
import math
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


In [2]:
DATASET_PATH = "input/392-crypto-currency-pairs-at-minute-resolution/btcusd.csv"

In [3]:
df=pd.read_csv(DATASET_PATH)
data = df['close']

In [4]:
data = data.tolist()

In [5]:
len(data)

3750538

In [6]:
data = data[-1500000:]

In [7]:
len(data)

1500000

In [8]:
data = np.array(data)

In [9]:
print(data)

[ 5167.75808232  5167.8         5168.6        ... 39029.
 39092.         39069.        ]


In [10]:
print(np.min(data), np.max(data))

4030.1 68925.0


In [11]:
def make_data(data,train):
    X_train = []
    y_train = []
    X_val = []
    y_val = []
    
    X_total = []
    y_total = []
    
    X_eql = []
    X_inc = []
    X_dec = []

    y_eql = []
    y_inc = []
    y_dec = []
    
    len_eql = 0
    len_inc = 0
    len_dec = 0
    
    for i in range(len(data)-401):
        
        X = data[i:i+400]
        mx = np.max(X)
        X = (X/mx)*0.9
        
        
        if data[i+400]>data[i+399]:
            y = [1,0,0]
            y_inc.append(y)
            len_inc+=1
            X_inc.append(X)
        if data[i+400]==data[i+399]:
            y = [0,1,0]
            y_eql.append(y)
            len_eql+=1
            X_eql.append(X)
        if data[i+400]<data[i+399]:
            y = [0,0,1]
            y_dec.append(y)
            len_dec+=1
            X_dec.append(X)
        
    length = min(len_inc,len_eql,len_dec)

    y_total = y_inc[:length] + y_eql[:length] + y_dec[:length]
    X_total = X_inc[:length] + X_eql[:length] + X_dec[:length]

    len_train = int(len(y_total)*train)
        
    X_train = X_total[:len_train]
    y_train = y_total[:len_train]
    
    X_val = X_total[-len_train:]
    y_val = y_total[-len_train:]
    
    X_train = np.array(X_train).reshape(-1,400,1)
    y_train = np.array(y_train).reshape(-1,3)
    X_val = np.array(X_val).reshape(-1,400,1)
    y_val = np.array(y_val).reshape(-1,3)


    
    return X_train, y_train, X_val, y_val


In [12]:
X_train, y_train, X_val, y_val = make_data(data,0.96)

In [13]:
y_train[0]

array([1, 0, 0])

In [14]:
X_train[0]

array([[0.89370605],
       [0.89386167],
       [0.89393084],
       [0.89394813],
       [0.89393554],
       [0.89505476],
       [0.89531412],
       [0.89526964],
       [0.8955562 ],
       [0.89583285],
       [0.89583288],
       [0.8955389 ],
       [0.89564265],
       [0.89581556],
       [0.89581556],
       [0.89581556],
       [0.89602305],
       [0.89602305],
       [0.89723343],
       [0.89723128],
       [0.89723343],
       [0.89721614],
       [0.89721614],
       [0.89721614],
       [0.89721614],
       [0.89721614],
       [0.89723343],
       [0.89725071],
       [0.89799424],
       [0.89808069],
       [0.89808586],
       [0.89808069],
       [0.89782133],
       [0.89780403],
       [0.89780403],
       [0.89780403],
       [0.89781395],
       [0.89780403],
       [0.89781395],
       [0.89781395],
       [0.89782133],
       [0.89782133],
       [0.89780403],
       [0.89782133],
       [0.89782133],
       [0.89782133],
       [0.89809798],
       [0.898

In [15]:
print(type(y_train[0]))

<class 'numpy.ndarray'>


In [16]:
y_train[10:20]

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]])